### ISSUE TITLE
Option --logging-config crash the decider

### ISSUE THREAD

**Issue by pior** [pior/caravan#3]
```
Traceback (most recent call last):
  File "bin/caravan-decider", line 14, in <module>
    sys.exit(Command.main())
  File "/opt/python-postalx/local/lib/python2.7/site-packages/caravan/commands/base.py", line 26, in main
    cmd._setup_logging()
  File "/opt/python-postalx/local/lib/python2.7/site-packages/caravan/commands/base.py", line 95, in _setup_logging
    logging.config.fileConfig(self.args.logging_config)
AttributeError: 'module' object has no attribute 'config'
```

**Comment by pior** [comment]
Fixed in 74c77462ff79b2991574a65e42e4806e33331656
